// Login captcha: a 4-character alphanumeric code rendered into a distorted PNG
// image, with the expected code carried in a stateless HMAC-signed cookie (same
// pattern as the admin session) rather than server-side storage. The image is
// generated by GET /admin/captcha.png — the only place a code is minted — and the
// cookie it sets is consumed (cleared) on every POST /admin/login attempt
// regardless of outcome, so a solved code can never be replayed: the next attempt
// must load a fresh image first. No external service, no API key.
package handler

import (
	"bytes"
	"crypto/hmac"
	"crypto/rand"
	"crypto/sha256"
	"crypto/subtle"
	"encoding/base64"
	"image"
	"image/color"
	"image/draw"
	"image/png"
	"math"
	"math/big"
	mrand "math/rand"
	"net/http"
	"strconv"
	"strings"
	"time"

	"golang.org/x/image/font"
	"golang.org/x/image/font/basicfont"
	"golang.org/x/image/math/fixed"
)

const captchaCookieName = "licadmin_captcha"
const captchaTTL = 3 * time.Minute
const captchaCodeLen = 4

// Excludes 0/O, 1/I/L and similar look-alikes so a correctly-read code is never
// rejected for being transcribed with the "wrong" visually-identical character.
const captchaCharset = "ABCDEFGHJKMNPQRSTUVWXYZ23456789"

const captchaImgWidth = 160
const captchaImgHeight = 60

type captchaSigner struct {
	secret []byte
}

func newCaptchaSigner(secret string) *captchaSigner {
	return &captchaSigner{secret: []byte(secret)}
}

func generateCaptchaCode() string {
	b := make([]byte, captchaCodeLen)
	for i := range b {
		n, err := rand.Int(rand.Reader, big.NewInt(int64(len(captchaCharset))))
		idx := 0
		if err == nil {
			idx = int(n.Int64())
		}
		b[i] = captchaCharset[idx]
	}
	return string(b)
}

func (s *captchaSigner) sign(code string) string {
	exp := time.Now().Add(captchaTTL).Unix()
	payload := code + "." + strconv.FormatInt(exp, 10)
	mac := hmac.New(sha256.New, s.secret)
	mac.Write([]byte(payload))
	sig := base64.RawURLEncoding.EncodeToString(mac.Sum(nil))
	return payload + "." + sig
}

// verify checks the cookie's signature and expiry, then compares its embedded code
// against the user-submitted one (case-insensitive — the image renders uppercase
// but typing lowercase shouldn't fail a human).
func (s *captchaSigner) verify(token, submitted string) bool {
	parts := strings.Split(token, ".")
	if len(parts) != 3 {
		return false
	}
	code, expStr, sig := parts[0], parts[1], parts[2]
	mac := hmac.New(sha256.New, s.secret)
	mac.Write([]byte(code + "." + expStr))
	expectedSig := base64.RawURLEncoding.EncodeToString(mac.Sum(nil))
	if subtle.ConstantTimeCompare([]byte(sig), []byte(expectedSig)) != 1 {
		return false
	}
	exp, err := strconv.ParseInt(expStr, 10, 64)
	if err != nil || time.Now().Unix() > exp {
		return false
	}
	submitted = strings.ToUpper(strings.TrimSpace(submitted))
	return subtle.ConstantTimeCompare([]byte(code), []byte(submitted)) == 1
}

func (s *captchaSigner) setCookie(w http.ResponseWriter, code string) {
	http.SetCookie(w, &http.Cookie{
		Name:     captchaCookieName,
		Value:    s.sign(code),
		Path:     "/admin",
		HttpOnly: true,
		SameSite: http.SameSiteLaxMode,
		MaxAge:   int(captchaTTL.Seconds()),
	})
}

// clearCookie runs after every login attempt, success or failure, so a solved
// code can never be replayed — the next attempt must load a fresh image first.
func (s *captchaSigner) clearCookie(w http.ResponseWriter) {
	http.SetCookie(w, &http.Cookie{
		Name:     captchaCookieName,
		Value:    "",
		Path:     "/admin",
		HttpOnly: true,
		SameSite: http.SameSiteLaxMode,
		MaxAge:   -1,
	})
}

func (s *captchaSigner) verifyRequest(r *http.Request) bool {
	cookie, err := r.Cookie(captchaCookieName)
	if err != nil {
		return false
	}
	return s.verify(cookie.Value, r.FormValue("captcha_answer"))
}

// ServeImage mints a fresh code, signs it into the response cookie, and writes a
// distorted PNG rendering of it. This is what every <img> tag on the login page
// points at; the code never appears anywhere except inside that image.
func (s *captchaSigner) ServeImage(w http.ResponseWriter, r *http.Request) {
	code := generateCaptchaCode()
	s.setCookie(w, code)

	w.Header().Set("Content-Type", "image/png")
	w.Header().Set("Cache-Control", "no-store, no-cache, must-revalidate")
	w.Header().Set("Pragma", "no-cache")

	var buf bytes.Buffer
	if err := png.Encode(&buf, renderCaptchaImage(code)); err != nil {
		http.Error(w, "gagal membuat captcha", http.StatusInternalServerError)
		return
	}
	w.Write(buf.Bytes()) //nolint:errcheck
}

var captchaTextColors = []color.RGBA{
	{30, 64, 175, 255},  // blue
	{22, 101, 52, 255},  // green
	{153, 27, 27, 255},  // red
	{88, 28, 135, 255},  // purple
	{120, 53, 15, 255},  // brown
}

// renderCaptchaImage draws code onto a noisy background, one character at a time:
// each glyph is rendered at native bitmap-font size, scaled up, rotated by a small
// random angle, and composited at a jittered position — enough distortion to
// defeat naive OCR without needing an external captcha service.
func renderCaptchaImage(code string) image.Image {
	seed, _ := rand.Int(rand.Reader, big.NewInt(math.MaxInt64))
	rng := mrand.New(mrand.NewSource(seed.Int64())) //nolint:gosec // visual jitter only; code itself comes from crypto/rand

	img := image.NewRGBA(image.Rect(0, 0, captchaImgWidth, captchaImgHeight))
	draw.Draw(img, img.Bounds(), &image.Uniform{color.RGBA{240, 242, 245, 255}}, image.Point{}, draw.Src)

	drawNoiseLines(img, rng, 3)
	drawNoiseDots(img, rng, 80)

	const scale = 4
	slot := captchaImgWidth / len(code)
	for i, ch := range code {
		glyph := renderGlyph(ch, captchaTextColors[rng.Intn(len(captchaTextColors))])
		glyph = scaleNearest(glyph, scale)
		angle := (rng.Float64()*2 - 1) * 0.35 // ~ -20..20 degrees, in radians
		glyph = rotateRGBA(glyph, angle)

		gb := glyph.Bounds()
		x := i*slot + (slot-gb.Dx())/2 + rng.Intn(9) - 4
		y := (captchaImgHeight-gb.Dy())/2 + rng.Intn(9) - 4
		draw.Draw(img, image.Rect(x, y, x+gb.Dx(), y+gb.Dy()), glyph, gb.Min, draw.Over)
	}

	drawNoiseDots(img, rng, 40)
	return img
}

// renderGlyph draws a single character onto a small transparent canvas using the
// standard-library bitmap font (basicfont.Face7x13 is ~6x13px per glyph).
func renderGlyph(ch rune, textColor color.RGBA) *image.RGBA {
	const w, h = 12, 18
	dst := image.NewRGBA(image.Rect(0, 0, w, h))
	d := &font.Drawer{
		Dst:  dst,
		Src:  image.NewUniform(textColor),
		Face: basicfont.Face7x13,
		Dot:  fixed.Point26_6{X: fixed.I(2), Y: fixed.I(13)},
	}
	d.DrawString(string(ch))
	return dst
}

func scaleNearest(src *image.RGBA, factor int) *image.RGBA {
	b := src.Bounds()
	w, h := b.Dx(), b.Dy()
	dst := image.NewRGBA(image.Rect(0, 0, w*factor, h*factor))
	for y := 0; y < h; y++ {
		for x := 0; x < w; x++ {
			c := src.RGBAAt(b.Min.X+x, b.Min.Y+y)
			for dy := 0; dy < factor; dy++ {
				for dx := 0; dx < factor; dx++ {
					dst.SetRGBA(x*factor+dx, y*factor+dy, c)
				}
			}
		}
	}
	return dst
}

// rotateRGBA rotates src around its own center by angle radians, sampling with
// nearest-neighbor; pixels landing outside the source stay fully transparent so
// the rotated glyph composites cleanly over the background.
func rotateRGBA(src *image.RGBA, angle float64) *image.RGBA {
	b := src.Bounds()
	w, h := b.Dx(), b.Dy()
	cx, cy := float64(w)/2, float64(h)/2
	sin, cos := math.Sin(angle), math.Cos(angle)
	dst := image.NewRGBA(image.Rect(0, 0, w, h))
	for y := 0; y < h; y++ {
		for x := 0; x < w; x++ {
			dx := float64(x) - cx
			dy := float64(y) - cy
			sx := dx*cos + dy*sin + cx
			sy := -dx*sin + dy*cos + cy
			ix, iy := int(math.Round(sx)), int(math.Round(sy))
			if ix >= 0 && ix < w && iy >= 0 && iy < h {
				dst.SetRGBA(x, y, src.RGBAAt(b.Min.X+ix, b.Min.Y+iy))
			}
		}
	}
	return dst
}

func drawNoiseLines(img *image.RGBA, rng *mrand.Rand, count int) {
	b := img.Bounds()
	for l := 0; l < count; l++ {
		c := color.RGBA{uint8(160 + rng.Intn(50)), uint8(160 + rng.Intn(50)), uint8(160 + rng.Intn(50)), 255}
		amp := 4 + rng.Intn(6)
		phase := rng.Float64() * 6.28
		yBase := 10 + rng.Intn(b.Dy()-20)
		for x := 0; x < b.Dx(); x++ {
			y := yBase + int(float64(amp)*math.Sin(float64(x)*0.08+phase))
			if y >= 0 && y < b.Dy() {
				img.SetRGBA(x, y, c)
			}
		}
	}
}

func drawNoiseDots(img *image.RGBA, rng *mrand.Rand, count int) {
	b := img.Bounds()
	for i := 0; i < count; i++ {
		x := rng.Intn(b.Dx())
		y := rng.Intn(b.Dy())
		v := uint8(170 + rng.Intn(60))
		img.SetRGBA(x, y, color.RGBA{v, v, v, 255})
	}
}
